### ISSUE TITLE
(sorry)

### ISSUE THREAD

**Issue by GoldenVadim** [FullPenetrationTesting/888-RAT#2]
(sorry)

**Comment by FullPenetrationTesting** [comment]
Even I Downloaded Cracked Version Of 888 Rat From A Phishy Site For This Repo, Obviously Its an Malware (bcz This Shit Is Cracked By Some Unknown Guy)
This repo is for Jdk Error Solving For All 888 RAT Users. Its tottaly upon you, you gonna download this rat from here or not. Thanks....
